### ISSUE TITLE
it can't work 

### ISSUE THREAD

**Issue by zhysee** [sadeepj/crfasrnn_keras#16]
when I run run_demo.py, errors output 

Traceback (most recent call last):
  File "run_demo.py", line 46, in <module>
    main()
  File "run_demo.py", line 36, in main
    model = get_crfrnn_model_def()
  File "/home/zhengye/crfasrnn_keras/crfrnn_model.py", line 49, in get_crfrnn_model_def
    x = Conv2D(64, (3, 3), activation='relu', padding='valid', name='conv1_1')(x)
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 603, in __call__
  File "build/bdist.linux-x86_64/egg/keras/layers/convolutional.py", line 164, in call
  File "build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py", line 3183, in conv2d
AttributeError: 'module' object has no attribute 'convolution'

**Comment by sadeepj** [comment]
@zhysee This looks like a Keras issue. Can you please run a CNN example in Keras (e.g. https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py) and make sure your Keras installation works?

**Comment by sadeepj** [comment]
See also https://github.com/fchollet/keras/issues/6078 for more details.

**Comment by CHWangXing** [comment]
when I run run_demo.py, errors output like this：
Traceback (most recent call last):
  File "run_demo.py", line 25, in <module>
    from crfrnn_model import get_crfrnn_model_def
  File "/home/wang/crfasrnn_keras/crfrnn_model.py", line 28, in <module>
    from crfrnn_layer import CrfRnnLayer
  File "/home/wang/crfasrnn_keras/crfrnn_layer.py", line 28, in <module>
    custom_module = tf.load_op_library('./cpp/high_dim_filter.so')
  File "/home/wang/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/wang/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./cpp/high_dim_filter.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by CHWangXing** [comment]
my env is ubuntu14.04 and i also try in 16.x, however they have the same errors

**Comment by CHWangXing** [comment]
My pro has been solved. THX

**Comment by zyfsa** [comment]
@CHWangXing 你好，我是中国人，我想问一下你是怎么解决这个问题的啊？我现在也遇到了这个问题，我是直接运行./compile.sh，没有什么source的过程？麻烦告知

**Comment by CHWangXing** [comment]
g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC -I$TF_INC -I$TF_INC/external/nsync/public -O2 -L$TF_LIB -ltensorflow_framework
更改comple.sh文件内容即可，具体原因可以上网百度下。

**Comment by sadeepj** [comment]
The problem reported by @CHWangXing should now be fixed as we now have a Makefile script.

**Comment by liuleiBUAA** [comment]
@zyfsa Hi, where do you find compile.sh
