### ISSUE TITLE
Value error: dimension must be 4

### ISSUE THREAD

**Issue by dimimal** [sadeepj/crfasrnn_keras#25]
I have connected crfasrnn layer on top of CNN output as the code below shows.

```
input_shape  = (img_rows,img_cols,
output_shape = (img_rows, img_cols, NUM_CLASSES) 
input_1 = Input(shape=model.output_shape)
input_2 = Input(shape=input_shape)
output1 = CrfRnnLayer(image_dims=(img_rows, img_cols),
                         num_classes=NUM_CLASSES,
                         theta_alpha=160.,
                         theta_beta=3.,
                         theta_gamma=3.,
                         num_iterations=10,
                         name='crfrnn')([input_1, input_2])

```
```

    model       = Model(inputs=model.input, outputs=model.output, name='CNN')

    top_model   = Model(inputs=[input_1, input_2], outputs=output1, name='CRF-RNN') 

    full_model  = Model(inputs=model.input, outputs=top_model([model.output, model.input]), name='Full')
```

But i get the following error, CNN yields a feature map of size of [batch_size, 512,512,20] where batch size equals to 1. I can't understand the error, the tensor's dimension is 4, has anyone any idea about that error?

```Traceback (most recent call last):
  File "./trainCRF.py", line 409, in <module>
    main()
  File "./trainCRF.py", line 407, in main
    crfRNN()
  File "./trainCRF.py", line 321, in crfRNN
    name='crfrnn')([input_1, input_2])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "./crfasrnn_keras/src/crfrnn_layer.py", line 77, in call
    unaries = tf.transpose(inputs[0][0, :, :, :], perm=(2, 0, 1))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1336, in transpose
    ret = gen_array_ops.transpose(a, perm, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 5694, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension must be 4 but is 3 for 'crfrnn/transpose' (op: 'Transpose') with input shapes: [?,512,512,20], [3].
```

**Comment by dimimal** [comment]
Ok, solved. I have changed  this line ```input_1 = Input(shape=model.output_shape) ``` with
 ``` input_1 = Input(shape=output_shape) ``` . I thought that could be the same.
