### ISSUE TITLE
Not Found Error Is Back..

### ISSUE THREAD

**Issue by leyuan** [sadeepj/crfasrnn_keras#27]
Hi there, I am using `tensorflow 1.6` as 1.4 was not working so I just upgraded it.
Running demo gives me this following error... Appreciate for your help!

```
(ds3.6) ~/D/u/8/crf-rnn ❯❯❯ python run_demo.py                                 master ◼
/Users/lucius/miniconda3/envs/ds3.6/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "run_demo.py", line 27, in <module>
    from crfrnn_model import get_crfrnn_model_def
  File "./src/crfrnn_model.py", line 28, in <module>
    from crfrnn_layer import CrfRnnLayer
  File "./src/crfrnn_layer.py", line 28, in <module>
    import high_dim_filter_loader
  File "./src/high_dim_filter_loader.py", line 28, in <module>
    custom_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'cpp', 'high_dim_filter.so'))
  File "/Users/lucius/miniconda3/envs/ds3.6/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/Users/lucius/miniconda3/envs/ds3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(./src/cpp/high_dim_filter.so, 6): Symbol not found: __ZN10tensorflow15OpKernelContext21CtxFailureWithWarningENS_6StatusE
  Referenced from: ./src/cpp/high_dim_filter.so
  Expected in: /Users/lucius/miniconda3/envs/ds3.6/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so
 in ./src/cpp/high_dim_filter.so
```

**Comment by Toz3wm** [comment]
I encountered similar problems when upgrading tensorflow. For me deleting and rebuilding high_dim_filter.so did the trick

**Comment by leyuan** [comment]
Thanks @Toz3wm !
